# Maximum laps for a party race
maxlaps: 100

# Time in seconds after first player finishes to end the race
endraceafterwin: 30

# Time in seconds after race starts to end the race
maxracetime: 3600

# Delay in seconds between sending invites to the same player, time in seconds before an invitation times out.
invitetimeout: 30

# Colours
primarycolour: '0260C6'
secondarycolour: '4cafff'
defaultcolour: 'ffffff'
acceptcolour: '23ff00'
denycolour: 'ff0000'
